name: "CLA signature check"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    uses: rdkcentral/cla_signatures/.github/workflows/cla.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT }}
