name: "CLA"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testingConcurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prerequisites
        run: |
          echo "test"
          sleep 60
          echo "test finished"
